# Generated by Django 4.1.5 on 2023-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.TextField(max_length=250),
        ),
    ]
