# Generated by Django 4.1.5 on 2023-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0002_alter_place_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='profile')),
                ('name', models.CharField(max_length=200)),
                ('role', models.TextField()),
            ],
        ),
    ]
